### PR TITLE
updated version to 1.12.5

### PR DESCRIPTION
**Pull request by adbeda**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adbeda** [comment]
@conda-forge-admin, please rerender

**Comment by adbeda** [comment]
@sodre / @stuarteberg, can you guys help me figure out why it keep failing on all checks but three? I keep thinking it could be a linting issue but never seem to be working right even after I fix those issues. Any help w'd be appreciated.

**Comment by sodre** [comment]
try restricting the package to only build using "nocgo", or setting "cgo to false" first. See if the build passes in that case.

**Comment by adbeda** [comment]
@sodre, `cgo` for linux failed although it passed for osx. `nocgo` works fine on both. from previous PR, i noticed that testing for windows failed too. if you look into the feedstock and point me to the files or lines of code i may need to review, I'll be happy to do that.

**Comment by adbeda** [comment]
@conda-forge/help-go is that something you had in mind ? you suggested restricting the package to only build using "nocgo" and i did that for `linux`

**Comment by scopatz** [comment]
The problem on windows is:

```
(C:\bld\go_1560879484972\_build_env) (base) C:\bld\go_1560879484972\work>call "C:\bld\go_1560879484972\_h_env\etc\conda\activate.d\activate-z60-go-nocgo.bat" 
The system cannot find the drive specified.
Building Go cmd/dist using C:\bld\go_1560879484972\_build_env\go1.4-bootstrap
go tool dist: mkdir D:\tmp\go-tool-dist-828099783: The system cannot find the path specified.
```

So it seems like the recipe no longer works

**Comment by adbeda** [comment]
@scopatz for windows, I think the test was disabled on [#56](https://github.com/conda-forge/go-feedstock/pull/56). @sodre and @stuarteberg worked on this and their input w'd be helpful.

**Comment by adbeda** [comment]
@sodre do you have thoughts on the latest PR for go? I submitted the PR based on your feedback.

**Comment by adbeda** [comment]
@conda-forge-admin please rerender

**Comment by sodre** [comment]
Try going back to conda build on3.16 for windows as well.

**Comment by sodre** [comment]
this was closed in #54

**Pull request closed without merging**
