### PR TITLE
fix up go patches to unblock build

### PR DESCRIPTION
**Pull request by achimgaedke**
Hey!

I'm trying to get the build process for go-1.19 unstuck. So I started re-adjusting the existing patches.

* Patch 0004 seemed to be easy.
* Patch 0007 might need a bit more love, as some of the patches are now addressed upstream
* Patch/Diff 0008 seems to be obsolete.

On a local linux build I run into trouble with the `race detector` test using the cgo build, the nocgo build is fine. This issue is similar to https://github.com/golang/go/issues/53522, but the build system's conda CDT glibc is 2.17.

I am not understanding much of conda's CDT/linking or of go itself, so I got that far, but need help.

```text
##### Testing race detector
# go tool dist test -run=^race$
# runtime/race.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-44950665/000002.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

FAIL	runtime/race [build failed]
FAIL
2022/09/16 04:08:37 Failed: exit status 2
# os.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-193081522/000002.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

# flag.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-1945294526/000020.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

FAIL	flag [build failed]
# encoding/gob.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-1371132106/000020.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

# net.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-3562864030/000020.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

FAIL	net [build failed]
FAIL	os [build failed]
# os/exec.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-1520527336/000024.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

FAIL	os/exec [build failed]
FAIL	encoding/gob [build failed]
FAIL
2022/09/16 04:08:39 Failed: exit status 2
# flag.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-3264798366/000020.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

FAIL	flag [build failed]
# os/exec.test
$PREFIX/go/pkg/tool/linux_amd64/link: running $PREFIX/bin/x86_64-conda-linux-gnu-cc failed: exit status 1
$PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/go-link-938424072/000024.o: in function `__sanitizer::MonotonicNanoTime()':
gotsan.cpp:(.text+0x1586d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

FAIL	os/exec [build failed]
FAIL
go tool dist: FAILED
```

### CODE REVIEW

**Comment by achimgaedke** [comment]
I have cleaned up the commits and removed the (probably) obsolete patches. I hope that is a better starting point for future investigations.

**Comment by achimgaedke** [comment]
Excellent! Another pattern of failures, ... `linux_64_cgofalsego_variant_strnocgogo_variant_ver2.2.0` now failing locally as well.

**Comment by hmaarrfk** [comment]
do you want to try building locally again? there has been a gcc bump. maybe that will help?

**Comment by hmaarrfk** [comment]
If you are looking for just a compiler bump, i'm trying to get that done in https://github.com/conda-forge/go-feedstock/pull/169

**Comment by tpdownes** [comment]
How far from a 1.19 release are we?  1.20 is [targeting February 2023 release](https://tip.golang.org/doc/go1.20).

**Comment by hmaarrfk** [comment]
i'm not sure what the question is.

help is appreciated if you can updated the patches and unblock the builds.

**Comment by jakirkham** [comment]
The general recommendation is to [build from source]( https://conda-forge.org/docs/orga/guidelines.html#compiled-objects )

**Comment by hmaarrfk** [comment]
There are some notes in:
https://github.com/conda-forge/go-feedstock/tree/main/recipe/patches#go-feedstock-patches

I might estimate that this is 1-10 hours of work for somebody that knows what they are doing. I'm just not sure.

**Comment by hmaarrfk** [comment]
We regularly inspire ourselves with patches from other sources.

These decisions are up to the maintainers.

You are free to volunteer and help get this accomplished.

**Comment by tpdownes** [comment]
I volunteer to maintain a number of packages. I have a lot less expertise once you get into "real" builds. Since you are a maintainer, you may choose to be inspired by these patches given how directly the anaconda packages were inspired by this work. However, if your goal is to inspire others to volunteer time for this package, you might choose a less sarcastic tone.

**Comment by hmaarrfk** [comment]
I'm sorry if it sounded sarcastic.

That really wasn't my intention. I meant to say that your suggestion is a good one. Here. It is really about trying.

I think if you can navigate looking at patches it might be a good thing to try.

I am happy to help review, but at the moment, given that go makes static binaries, i just don't have time to go through the patching myself, but can help in the review process if you wish to give an attempt.

**Pull request closed without merging**
