### PR TITLE
Update to 1.14.1

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

----

Just trying to figure out what's required to get #87 merged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Rebased on `master` (hopefully correctly!)

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
It seems the tests failed on Windows:
```
FAIL
go tool dist: Failed: exit status 1
# go tool dist test -run=^go_test:archive/tar$

(%PREFIX%) %SRC_DIR%>if errorlevel 1 exit 1 
Tests failed for go-1.14.1-h13ea7b9_0.tar.bz2 - moving package to D:\bld\broken
```

...which seems to be due to a missing `/tmp` folder:
```
bash.exe: warning: could not find /tmp, please create!
```
<details>

```

    --- FAIL: TestScript/get_brace (0.76s)
        script_test.go:198: 
            # Set up some empty repositories. (0.466s)
            # Clone the empty repositories into GOPATH.
            # This tells the Go command where to find them: it takes the place of a user's meta-tag redirector. (0.283s)
            > mkdir $GOPATH/src/example.com
            > cd $GOPATH/src/example.com
            $WORK\gopath/src/example.com
            > exec git clone $WORK/_origin/foo
            [stderr]
            Cloning into 'foo'...
            bash.exe: warning: could not find /tmp, please create!
            done.
            > exec git clone $WORK/_origin/{confusing}
            [stderr]
            Cloning into 'confusing'...
            bash.exe: warning: could not find /tmp, please create!
            fatal: '$WORK/_origin/confusing' does not appear to be a git repository
            fatal: Could not read from remote repository.
            
            Please make sure you have the correct access rights
            and the repository exists.
            [exit status 128]
            FAIL: testdata\script\get_brace.txt:24: unexpected command failure
```
</details>

**Comment by dhirschfeld** [comment]
The `-fdebug-prefix-map` looks a bit suspect:
```
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=%PREFIX%\tmp\go-build045927838=/tmp/go-build -gno-record-gcc-switches
```

**Comment by dhirschfeld** [comment]
Thanks for taking a look @mbargull! I'm definitely out of my comfort-zone with this one 😬

**Comment by mbargull** [comment]
> Thanks for taking a look @mbargull! I'm definitely out of my comfort-zone with this one grimacing

:laughing: likewise, so no promises ;).
I've no idea why the macOS test failed (issues like https://github.com/golang/go/issues/35692 indicate that happens on ARM, but I couldn't see x86-related failure examples).
The Windows test might be something like `TMP` no being passed on, or it needs `TMPDIR` instead. No idea where to work around in case of the former; trying the latter (i.e., `TMPDIR`) first.

**Comment by dhirschfeld** [comment]
Newer go is now available.

**Pull request closed without merging**
