### PR TITLE
Update to 1.12

### PR DESCRIPTION
**Pull request by sodre**
xref: #53

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
Recipe fails to lint, but that is kinda normal

**Comment by mrocklin** [comment]
Checking in, what's the status here?  Is there anything we can do to push on this?  It'd be handy for some Dask work.

**Comment by mrocklin** [comment]
(cc @jakirkham)

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Comment by mrocklin** [comment]
For context, I ran into this when trying to install [dask-gateway](https://github.com/jcrist/dask-gateway) (which I imagine is also why @jcrist cares about this)

**Comment by scopatz** [comment]
Any help is welcome on this!

**Comment by stuarteberg** [comment]
I don't have much to offer, but here's what I see so far.

The errors on Windows and Linux are different.  On Windows, the build fails with some problem in the recipe:

```
ValueError: All packages in zip keys must belong to only one group.  'None' is in more than one group.
```

Presumably, that's referring to some sort of problem in [`conda_build_config.yaml`](https://github.com/conda-forge/go-feedstock/blob/master/recipe/conda_build_config.yaml), but I don't see anything obviously wrong there.

Meanwhile, one of the linux configurations fails with error messages like this:
```
runtime/cgo(.text.fatalf): relocation target stderr not defined for ABI0 (but is defined for ABI0)
```

Googling for that leads you to the following comment from none other than our good friend @jakirkham:
https://github.com/golang/go/issues/23649#issuecomment-493248154

So, I guess someone should try adding `-ldflags="-linkmode=external"` to some line in `build-core.sh`?  I'm not quite sure where, though....

**Comment by mariusvniekerk** [comment]
this might go into the CGO_LDFRAGS env var?

**Comment by mariusvniekerk** [comment]
unclear where this goes now?

**Comment by mariusvniekerk** [comment]
Seems cgo is REALLY wanting something called gcc during its bootstrap phase, so maybe some symlinks?

**Comment by mariusvniekerk** [comment]
Not entirely sure if cgo is correct here, but it does build??

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
@sodre Should we just merge this and fix the windows part in a follow on?

**Comment by scopatz** [comment]
I am OK with that

**Comment by jakirkham** [comment]
Raised issue ( https://github.com/conda-forge/go-feedstock/issues/63 ) on the Windows build failure for tracking purposes.

**Comment by adbeda** [comment]
@mariusvniekerk /@sodre did this PR updated just go for linux? The osx version [anaconda/conda-forge](https://anaconda.org/conda-forge/go) still says 1.11.9. If so, w'd creating a PR to update for osx make sense?

**Comment by jakirkham** [comment]
For some reason the macOS build passed, but the upload failed. Have restarted in the event that fixes things.

**Pull request merged**
