### PR TITLE
Update conda_build_config.yaml

### PR DESCRIPTION
**Pull request by agcopenhaver**
remove osx blocks

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
@stuarteberg It still doesn't build for windows, but builds cgo for osx, unlike previous build

**Comment by sodre** [comment]
Now that the variants issue is fixed, there is a problem with conda-build and the conda_package_handling package only on windows...

I will try to use conda-build 3.16 instead and see if that works better.

**Comment by sodre** [comment]
We have some progress now, and we the build is failing because the azure Windows VMs already include a version of go different from the one in conda-forge.

The next step is to remove it before the build starts.

**Comment by sodre** [comment]
I'm disabling the build on windows.... we'll come back to it at a later time.

**Pull request merged**
