### PR TITLE
Bump version to 1.10

### PR DESCRIPTION
**Pull request by nehaljwani**
Don't merge this!

### CODE REVIEW

**Comment by jakirkham** [comment]
> Don't merge this!

Umm... 😕

**Comment by nehaljwani** [comment]
@jakirkham Could you move the 1.10 binaries to broken label? They contain a cache directory of objects which increases the size of the package significantly. I am working on a fix right now.

**Comment by jakirkham** [comment]
Done.

In the future, we can tell the feedstock to upload those binaries under a different label like `test`.

**Comment by nehaljwani** [comment]
How to do that?

**Comment by jakirkham** [comment]
1. Create a new branch (e.g. `test`)
2. Add the code below to `conda-forge.yml`
3. Re-render

```yaml
channels:
  targets:
    - [conda-forge, test]
```

Example in PR ( https://github.com/conda-forge/hdf5-feedstock/pull/32 ).

**Pull request merged**
