### PR TITLE
Bump version to 1.16.3

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/go-feedstock/issues/104

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin Please re-render!

**Comment by nehaljwani** [comment]
@conda-forge-admin Please re-render!

**Comment by jakirkham** [comment]
Thanks Nehal! 😄

Added a closes note in the OP. Hope that is ok 🙂

**Comment by nehaljwani** [comment]
@jakirkham Thank you for adding that!

**Pull request merged**
