### PR TITLE
Bump to 1.14.1

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by joseph-zhong** [comment]
Hi, thanks for working on this!
I was interested in checking-in on the progress of this PR? I have a PR to add a new recipe which I've verified that it builds successfully with go=1.14 which doesn't currently seem available. Thanks!

**Comment by scopatz** [comment]
I think this could be updated now

**Comment by dhirschfeld** [comment]
It would be great to get this in as some `terraform` recipes are now wanting `go=1.14`

image

**Comment by shoemakerdr** [comment]
Is there any update on this PR? Go is now at version 1.15. Would love to use the latest go and have it be managed by conda. Thanks!

**Pull request closed without merging**
